import { Discussion, Reply } from "./communityTypes";

export const MOCK_DISCUSSIONS: Discussion[] = [
  {
    id: "disc-1",
    topic: "sleep",
    title: "14-month-old suddenly fighting afternoon naps",
    body: "My toddler was napping consistently for 1.5 hours every afternoon. Over the past week, she screams the moment she's placed in her crib. Is this the 14-month sleep regression or is she trying to drop to one nap?",
    author_initial: "S",
    author_child_age_months: 14,
    reply_count: 8,
    expert_reply: {
      id: "exp-1",
      expert_name: "Dr. Priya Sharma",
      credential: "Pediatrician",
      body: "Sleep shifts around 12–15 months are very common and often coincide with motor development leaps (like walking or climbing). Before dropping to a single nap, test keeping wake windows 15–20 minutes longer in the morning. Most toddlers aren't fully ready for one nap until 15–18 months.",
      created_at: "2 hours ago",
      is_verified: true,
    },
    created_at: "3 hours ago",
    age_relevance_min: 10,
    age_relevance_max: 20,
    saved: false,
  },
  {
    id: "disc-2",
    topic: "feeding",
    title: "Weaning tips & texture refusal at 8 months",
    body: "We started finger foods two weeks ago, but he gags and spits out anything chunkier than smooth puree. How did you transition your baby to mashed/lumpy textures without panicking?",
    author_initial: "M",
    author_child_age_months: 8,
    reply_count: 12,
    expert_reply: {
      id: "exp-2",
      expert_name: "Ananya Roy",
      credential: "Pediatric Nutritionist",
      body: "Gagging is a protective reflex located near the front of the tongue at this stage. It is completely normal and differs from choking! Try offering soft resistive foods like cooked carrot sticks or avocado spears that he can hold and explore at his own pace.",
      created_at: "5 hours ago",
    },
    created_at: "6 hours ago",
    age_relevance_min: 6,
    age_relevance_max: 12,
    saved: true,
  },
  {
    id: "disc-3",
    topic: "milestones",
    title: "When did your little one start pointing to show interest?",
    body: "She points to things she wants (imperative pointing), but hasn't started pointing just to show me things she finds interesting (declarative pointing) at 13 months. Should I practice this with her daily?",
    author_initial: "K",
    author_child_age_months: 13,
    reply_count: 6,
    expert_reply: {
      id: "exp-3",
      expert_name: "Rohan Mehta",
      credential: "Child Development Specialist",
      body: "Declarative pointing typically emerges between 12 and 16 months. You can model this by pointing during outdoor walks while saying 'Look, a doggie!' with enthusiastic facial expressions. No stress required!",
      created_at: "1 day ago",
    },
    created_at: "1 day ago",
    age_relevance_min: 10,
    age_relevance_max: 18,
    saved: false,
  },
  {
    id: "disc-4",
    topic: "behaviour",
    title: "Handling big tantrums during diaper changes",
    body: "Every single diaper change has turned into a wrestling match at 18 months. She arches her back and screams. What gentle distractor games or routines worked for your family?",
    author_initial: "A",
    author_child_age_months: 18,
    reply_count: 15,
    expert_reply: null,
    created_at: "4 hours ago",
    age_relevance_min: 12,
    age_relevance_max: 30,
    saved: false,
  },
  {
    id: "disc-5",
    topic: "health",
    title: "Post-vaccination low fever & fussiness at 6 months",
    body: "Got 6-month shots yesterday morning. Temperature is around 99.8°F and baby is extra clingy. How long did the post-vax tiredness last for your little ones?",
    author_initial: "R",
    author_child_age_months: 6,
    reply_count: 9,
    expert_reply: {
      id: "exp-4",
      expert_name: "Dr. Priya Sharma",
      credential: "Pediatrician",
      body: "Mild low-grade fever and fussiness for 24–48 hours after routine vaccinations are standard signs of the immune system building antibodies. Keep baby hydrated with extra nursing/formula feeds and skin-to-skin contact.",
      created_at: "12 hours ago",
      is_verified: true,
    },
    created_at: "14 hours ago",
    age_relevance_min: 4,
    age_relevance_max: 8,
    saved: false,
  },
  {
    id: "disc-6",
    topic: "play",
    title: "Simple indoor activities for rainy days with a 2-year-old",
    body: "Looking for low-prep activities that don't involve screen time. We've done sensory bins with rice and water play. What are your favorite quick ideas?",
    author_initial: "D",
    author_child_age_months: 25,
    reply_count: 11,
    expert_reply: null,
    created_at: "1 day ago",
    age_relevance_min: 18,
    age_relevance_max: 36,
    saved: false,
  },
  {
    id: "disc-7",
    topic: "development",
    title: "Language explosion at 22 months — repeating everything!",
    body: "Suddenly over the last 2 weeks, he went from 20 words to mimicking entire 3-word sentences. Anyone else amazed by how quickly their comprehension expands around this stage?",
    author_initial: "N",
    author_child_age_months: 22,
    reply_count: 7,
    expert_reply: null,
    created_at: "2 days ago",
    age_relevance_min: 18,
    age_relevance_max: 30,
    saved: false,
  },
  {
    id: "disc-8",
    topic: "sleep",
    title: "Newborn day/night confusion — 3 weeks old",
    body: "Our baby sleeps peacefully all day long from 9am to 6pm, then stays wide awake and alert from midnight to 4am. How long until their circadian rhythm settles?",
    author_initial: "J",
    author_child_age_months: 1,
    reply_count: 14,
    expert_reply: {
      id: "exp-5",
      expert_name: "Dr. Kavita Nambiar",
      credential: "Infant Sleep Consultant",
      body: "Circadian rhythms start producing melatonin naturally around 8–12 weeks. Right now, expose your baby to bright indirect sunlight during daytime feeds, and keep nighttime feeds pitch dark with low whispering.",
      created_at: "1 day ago",
      is_verified: true,
    },
    created_at: "2 days ago",
    age_relevance_min: 0,
    age_relevance_max: 3,
    saved: false,
  },
];

export const MOCK_REPLIES: Record<string, Reply[]> = {
  "disc-1": [
    {
      id: "r-101",
      discussion_id: "disc-1",
      author_initial: "P",
      author_child_age_months: 15,
      body: "We went through the exact same thing at 14 months! It lasted about 10 days. We stuck strictly to bedtime routines and didn't drop the nap yet. She went back to normal soon after.",
      is_expert: false,
      created_at: "2 hours ago",
    },
    {
      id: "r-102",
      discussion_id: "disc-1",
      author_initial: "L",
      author_child_age_months: 13,
      body: "What worked for us was shifting lunch 15 minutes earlier and giving her a quiet book in crib for 10 minutes before soothing. Hang in there!",
      is_expert: false,
      created_at: "1 hour ago",
    },
  ],
  "disc-2": [
    {
      id: "r-201",
      discussion_id: "disc-2",
      author_initial: "T",
      author_child_age_months: 9,
      body: "Steamed sweet potato sticks were our lifesaver! They're super soft so even if baby bites off a chunk, it squishes instantly.",
      is_expert: false,
      created_at: "4 hours ago",
    },
  ],
  "disc-4": [
    {
      id: "r-401",
      discussion_id: "disc-4",
      author_initial: "E",
      author_child_age_months: 19,
      body: "We give our toddler a special 'diaper-only toy' (a small flashlight or musical shaker) that he ONLY gets to hold during changes. Works 90% of the time!",
      is_expert: false,
      created_at: "3 hours ago",
    },
    {
      id: "r-402",
      discussion_id: "disc-4",
      author_initial: "V",
      author_child_age_months: 17,
      body: "Standing diaper changes for wet diapers helped us tremendously! Pant-style diapers make this super easy.",
      is_expert: false,
      created_at: "2 hours ago",
    },
  ],
};
