/**
 * Row shapes for every table the client touches.
 *
 * Hand-written rather than generated by `supabase gen types` because the
 * CLI isn't authenticated here. Regenerating later is the right move —
 * these are deliberately named to match, so the swap is mechanical.
 *
 * The enums must stay in step with supabase/migrations/…_core_schema.sql.
 * DOMAIN_ORDER below is also the plan's presentation order.
 */

export const DOMAINS = ["motor", "communication", "cognitive", "social_emotional"] as const;
export type Domain = (typeof DOMAINS)[number];

export const AGE_BANDS = [
  "m0_3",
  "m4_6",
  "m7_12",
  "m13_24",
  "m25_36",
  "y3_5",
  "y5_7",
] as const;
export type AgeBand = (typeof AGE_BANDS)[number];

/** Labels for display. The DB stores the enum; the UI never shows it raw. */
export const DOMAIN_LABEL: Record<Domain, string> = {
  motor: "Motor",
  communication: "Communication",
  cognitive: "Cognitive",
  social_emotional: "Social & Emotional",
};

export const AGE_BAND_LABEL: Record<AgeBand, string> = {
  m0_3: "0–3 months",
  m4_6: "4–6 months",
  m7_12: "7–12 months",
  m13_24: "13–24 months",
  m25_36: "25–36 months",
  y3_5: "3–5 years",
  y5_7: "5–7 years",
};

// --- Global content ---------------------------------------------------

export type Activity = {
  id: string;
  domain: Domain;
  age_band: AgeBand;
  title: string;
  why: string;
  duration_minutes: number;
  materials: string;
  instructions: string | null;
};

export type Milestone = {
  id: string;
  domain: Domain;
  age_band: AgeBand;
  stage_label: string;
  description: string;
  typical_age_min_months: number;
  typical_age_max_months: number;
  guide: { try?: string; watch?: string; see?: string } | null;
};

/**
 * How a vaccine is positioned for a parent.
 *
 *   essential   — India's Universal Immunisation Programme. Free at
 *                 government facilities; the baseline every child gets.
 *   recommended — IAP advises it beyond the UIP, for broader protection.
 *   situational — only for specific geography, risk or medical need, and
 *                 never presented as something a typical child is missing.
 */
export const VACCINE_TIERS = ["essential", "recommended", "situational"] as const;
export type VaccineTier = (typeof VACCINE_TIERS)[number];

export const VACCINE_TIER_LABEL: Record<VaccineTier, string> = {
  essential: "Essential",
  recommended: "Recommended",
  situational: "Situational",
};

export const VACCINE_TIER_BLURB: Record<VaccineTier, string> = {
  essential: "Part of India's Universal Immunisation Programme — free at government centres.",
  recommended: "Advised by the Indian Academy of Pediatrics for broader protection.",
  situational: "Only needed for specific risks, places or medical conditions. Ask your doctor.",
};

export type VaccinationScheduleItem = {
  id: string;
  vaccine_name: string;
  tier: VaccineTier;
  /** Display string — real schedules are ranges ("16–24 months"). */
  age_label: string;
  /** Exact age in days; the sort key. */
  age_days: number;
  recommended_age_months: number;
  dose_label: string | null;
  notes: string | null;
  /** "NIS" (government) or "IAP" — every row is traceable. */
  source: string | null;
};

// --- Family data ------------------------------------------------------

export type Profile = {
  id: string;
  parent_name: string | null;
  relationship: string | null;
  phone: string | null;
  /** IANA zone. Every "today" in the product derives from this. */
  timezone: string;
  created_at: string;
};

export type Child = {
  id: string;
  parent_id: string;
  name: string;
  date_of_birth: string; // YYYY-MM-DD
  gender: string | null;
  created_at: string;
};

export type DailyPlanRow = {
  id: string;
  child_id: string;
  plan_date: string; // family-local date
  motor_activity_id: string | null;
  communication_activity_id: string | null;
  cognitive_activity_id: string | null;
  social_emotional_activity_id: string | null;
  swaps: Partial<Record<Domain, number>>;
  generated_at: string;
};

/** A plan with its activities resolved — what screens actually render. */
export type DailyPlan = {
  id: string;
  planDate: string;
  /** Always four, in DOMAIN order, nulls dropped. */
  activities: Activity[];
  swaps: Partial<Record<Domain, number>>;
};

/**
 * One row per activity per day. Created on Start, updated on Complete.
 *
 *   started_at set, completed_at null  -> in progress, or abandoned
 *   both set                           -> done
 *   started_at null, completed_at set  -> marked done without starting
 *
 * Only rows with `completed_at` count as done. Anything reading progress
 * must filter on that, not on the row existing.
 */
export type ActivityLogEntry = {
  id: string;
  child_id: string;
  activity_id: string | null;
  /** Snapshotted at write time — never re-read from `activities`. */
  domain: Domain;
  title: string;
  age_band: AgeBand;
  plan_date: string | null;
  started_at: string | null;
  completed_at: string | null;
  note: string | null;
  photo_path: string | null;
};

export type ChildMilestone = {
  id: string;
  child_id: string;
  milestone_id: string;
  achieved_at: string;
  note: string | null;
};

export type ChildVaccination = {
  id: string;
  child_id: string;
  vaccination_id: string;
  administered_on: string;
  notes: string | null;
};

export type CopilotConversation = {
  id: string;
  child_id: string;
  title: string | null;
  created_at: string;
  last_message_at: string;
};

export type CopilotMessage = {
  id: string;
  conversation_id: string;
  role: "parent" | "copilot";
  content: string;
  created_at: string;
};
