/**
 * Generates the global-content migration from the content that already
 * lives in the codebase — the 56 activities in lib/todaysPlan.ts and the
 * 199 milestones in the website's journeyStages.json.
 *
 * Generated rather than hand-written so it can't drift from the source,
 * and so re-running after a content edit is one command.
 *
 *   node scripts/gen-seed.mjs
 *
 * Emitted as a MIGRATION rather than supabase/seed.sql because seed.sql
 * only runs on a local `db reset` — it never reaches a remote project.
 * activities and milestones are read-only reference data that must exist
 * in every environment, so they belong in the migration history.
 *
 * Every statement is an idempotent upsert, so regenerating after a content
 * edit and pushing again updates rows in place rather than conflicting.
 *
 * vaccination_schedule is deliberately left empty — see the note it emits.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const JOURNEY = resolve(root, "../the-neighbourhood/src/data/journeyStages.json");

const DOMAIN_SQL = {
  Motor: "motor",
  Communication: "communication",
  Cognitive: "cognitive",
  "Social & Emotional": "social_emotional",
};

/** Activity bands, lower bound in months → enum label. */
const BANDS = [
  { from: 0, band: "m0_3" },
  { from: 4, band: "m4_6" },
  { from: 7, band: "m7_12" },
  { from: 13, band: "m13_24" },
  { from: 25, band: "m25_36" },
  { from: 37, band: "y3_5" },
  { from: 61, band: "y5_7" },
];

const bandFor = (months) => {
  let match = BANDS[0].band;
  for (const b of BANDS) if (months >= b.from) match = b.band;
  return match;
};

const q = (v) =>
  v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`;

const slug = (s) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

// ---------------------------------------------------------------------
// Activities — parsed out of the TS source.
//
// Reading the .ts directly (rather than importing it) keeps this script
// dependency-free; the file is a plain literal array with a fixed shape.
// ---------------------------------------------------------------------
const src = readFileSync(resolve(root, "lib/todaysPlan.ts"), "utf8");

const activities = [];
const bandBlocks = src.split(/\{\s*\n\s*from:\s*(\d+),/).slice(1);
for (let i = 0; i < bandBlocks.length; i += 2) {
  const from = Number(bandBlocks[i]);
  const body = bandBlocks[i + 1];
  const band = bandFor(from);

  const re =
    /domain:\s*"([^"]+)",\s*\n\s*title:\s*"([^"]+)",\s*\n\s*why:\s*"([^"]+)",\s*\n\s*durationMins:\s*(\d+),\s*\n\s*materials:\s*"([^"]+)"/g;
  let m;
  while ((m = re.exec(body))) {
    activities.push({
      id: slug(m[2]),
      domain: DOMAIN_SQL[m[1]],
      age_band: band,
      title: m[2],
      why: m[3],
      duration_minutes: Number(m[4]),
      materials: m[5],
    });
  }
}

// ---------------------------------------------------------------------
// Milestones — from the website's dataset.
// ---------------------------------------------------------------------
/** "10–12 months" / "3–4 years" → [minMonths, maxMonths]. */
function parseStage(label) {
  const years = /year/i.test(label);
  const nums = label.match(/\d+/g)?.map(Number) ?? [0];
  const [a, b = a] = nums;
  return years ? [a * 12, b * 12] : [a, b];
}

const milestones = [];
if (existsSync(JOURNEY)) {
  const stages = JSON.parse(readFileSync(JOURNEY, "utf8"));
  for (const stage of stages) {
    const [minM, maxM] = parseStage(stage.label);
    for (const dom of stage.domains) {
      const domain = DOMAIN_SQL[dom.name];
      if (!domain) continue;
      for (const ms of dom.milestones ?? []) {
        milestones.push({
          id: `${slug(stage.label)}-${domain}-${slug(ms.text)}`.slice(0, 200),
          domain,
          age_band: bandFor(minM),
          stage_label: stage.label,
          description: ms.text,
          typical_age_min_months: minM,
          typical_age_max_months: maxM,
          guide: ms.guide ? JSON.stringify(ms.guide) : null,
        });
      }
    }
  }
}

// ---------------------------------------------------------------------
// Emit
// ---------------------------------------------------------------------
const lines = [];
lines.push("-- GENERATED by scripts/gen-seed.mjs — do not edit by hand.");
lines.push("-- Regenerate after any content change:  node scripts/gen-seed.mjs");
lines.push("--");
lines.push(`-- activities: ${activities.length}   milestones: ${milestones.length}`);
lines.push("--");
lines.push("-- Idempotent: every statement upserts, so re-pushing after a content");
lines.push("-- edit updates rows in place. No begin/commit — the CLI already wraps");
lines.push("-- each migration in a transaction.");
lines.push("");

lines.push("-- Activities ---------------------------------------------------------");
if (activities.length) {
  lines.push(`delete from activities where id not in (${activities.map(a => q(a.id)).join(", ")});`);
}
lines.push(
  "insert into activities (id, domain, age_band, title, why, duration_minutes, materials) values"
);
lines.push(
  activities
    .map(
      (a) =>
        `  (${q(a.id)}, ${q(a.domain)}::domain, ${q(a.age_band)}::age_band, ${q(a.title)}, ${q(a.why)}, ${a.duration_minutes}, ${q(a.materials)})`
    )
    .join(",\n")
);
lines.push(
  "on conflict (id) do update set domain = excluded.domain, age_band = excluded.age_band, title = excluded.title, why = excluded.why, duration_minutes = excluded.duration_minutes, materials = excluded.materials;"
);
lines.push("");

lines.push("-- Milestones ---------------------------------------------------------");
if (milestones.length) {
  lines.push(`delete from milestones where id not in (${milestones.map(m => q(m.id)).join(", ")});`);
  lines.push(
    "insert into milestones (id, domain, age_band, stage_label, description, typical_age_min_months, typical_age_max_months, guide) values"
  );
  lines.push(
    milestones
      .map(
        (m) =>
          `  (${q(m.id)}, ${q(m.domain)}::domain, ${q(m.age_band)}::age_band, ${q(m.stage_label)}, ${q(m.description)}, ${m.typical_age_min_months}, ${m.typical_age_max_months}, ${m.guide ? `${q(m.guide)}::jsonb` : "null"})`
      )
      .join(",\n")
  );
  lines.push(
    "on conflict (id) do update set domain = excluded.domain, age_band = excluded.age_band, stage_label = excluded.stage_label, description = excluded.description, typical_age_min_months = excluded.typical_age_min_months, typical_age_max_months = excluded.typical_age_max_months, guide = excluded.guide;"
  );
} else {
  lines.push(`-- SKIPPED: ${JOURNEY} not found.`);
}
lines.push("");

lines.push("-- Vaccination schedule -----------------------------------------------");
lines.push("-- INTENTIONALLY EMPTY. No vaccination dataset exists in either repo,");
lines.push("-- and an immunisation schedule must come from a sourced IAP reference");
lines.push("-- rather than being reconstructed. Seed before shipping Vaccinations.");
lines.push("");

const OUT = "supabase/migrations/20260726092000_seed_content.sql";
writeFileSync(resolve(root, OUT), lines.join("\n") + "\n");
console.log(`wrote ${OUT}`);

// ---------------------------------------------------------------------
// Coverage report — the content gaps, per band per domain.
// ---------------------------------------------------------------------
const DOMAINS = ["motor", "communication", "cognitive", "social_emotional"];
const report = {};
for (const b of BANDS) report[b.band] = Object.fromEntries(DOMAINS.map((d) => [d, 0]));
for (const a of activities) report[a.age_band][a.domain] += 1;

console.log(`\nactivities: ${activities.length}   milestones: ${milestones.length}\n`);
console.log("ACTIVITIES per band per domain (2 = bare minimum for one swap)\n");
console.log(
  "band".padEnd(9) + DOMAINS.map((d) => d.slice(0, 6).padStart(8)).join("") + "   total"
);
for (const b of BANDS) {
  const row = report[b.band];
  const total = DOMAINS.reduce((s, d) => s + row[d], 0);
  console.log(
    b.band.padEnd(9) +
      DOMAINS.map((d) => String(row[d]).padStart(8)).join("") +
      `   ${total}`
  );
}

const mByBand = {};
for (const m of milestones) mByBand[m.age_band] = (mByBand[m.age_band] ?? 0) + 1;
console.log("\nMILESTONES per band");
for (const b of BANDS) console.log(`  ${b.band.padEnd(8)} ${mByBand[b.band] ?? 0}`);
console.log("\nvaccination_schedule: 0 — no source dataset exists.\n");
